version: "3.9"

services:
  db:
    image: postgres:16
    container_name: teslodb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecr3tPassword@as2
      POSTGRES_DB: TesloDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

