version: "3.9"

services:
  db:
    image: postgres:16
    container_name: teslodb
    restart: always

    ports:
      - "5435:5432"

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}

    volumes:
      - ./postgres:/var/lib/postgresql/data

    env_file:
      - .env.development
